### ISSUE TITLE
Will there be 2D and 3D human pose estimation code?

### ISSUE THREAD

**Issue by qizhen816** [mehtadushy/SelecSLS-Pytorch#1]
Hi,
Firstly, thanks for your splendid work and beautiful coding!
I'm a student mainly focusing on real-time 3D pose estimation. Your 3D demo is the best real-time 3D result I've ever seen. So, after the ImageNet demo, will you release 3D pose estimation code and model?

**Comment by mehtadushy** [comment]
Hi

At the moment we are not sure of the timeline of release of the 3D pose system due to the work still being unpublished. Also, the system implemented in the paper is in Caffe. Part of the purpose for releasing the imagenet reference in pytorch is to encourage the use of the network architecture for other tasks in  a more modern framework. Implementing the 2D pose part should be easy though, given that it uses the PAF approach of Cao et al. I will try to make trained examples of multiperson 2Dpose and segmentation available for wider use, which others can perhaps build upon to replicate the 3D pose system.
